[local]
localhost

[mongodb]
mongodb.sujitha-daws.online

[redis]
redis.sujitha-daws.online

[mysql]
mysql.sujitha-daws.online

[rabbitmq]
rabbitmq.sujitha-daws.online

[catalogue]
catalogue.sujitha-daws.online

[user]
user.sujitha-daws.online

[cart]
cart.sujitha-daws.online

[shipping]
shipping.sujitha-daws.online

[payment]
payment.sujitha-daws.online

[frontend]
frontend.sujitha-daws.online

[private-key-demo]
172.31.15.125